version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 100
  - package-ecosystem: "pip"
    directory: "/.ci_build"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
