---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build nikos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.23"

      - name: Cache Go modules
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build nikos
        run: bash .ci_build/build_install_nikos.sh .

      - name: Verify build
        run: /opt/nikos/bin/nikos

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: nikos-archive
          path: /opt/nikos
          retention-days: 1

  molecule-tests:
    name: Molecule tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            "fedora",
            "centos",
            "opensuse",
            "debian",
            "ubuntu",
            "oracle",
            "amazon-linux",
          ]
        test_type: ["host", "container"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.x"
          cache-dependency-path: .ci_build/requirements.txt

      - name: Install pip dependencies
        run: |
          pip install -r .ci_build/requirements.txt

      - name: Install virtualbox and vagrant
        run: |
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes -o /usr/share/keyrings/oracle-virtualbox-2016.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list

          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

          sudo apt-get update && sudo apt-get install gcc-12 virtualbox-7.1 vagrant

      - name: Download the nikos artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: nikos-archive
          path: tests/molecule/resources/playbooks/nikos-archive

      - name: Set nikos binary executable
        run: |
          chmod +x tests/molecule/resources/playbooks/nikos-archive/bin/nikos

      - name: Run molecule test
        working-directory: tests
        run: molecule test -s ${{ matrix.platform }}-${{ matrix.test_type }}
