---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build nikos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build nikos
        run: bash .ci_build/build_install_nikos.sh .

      - name: Verify build
        run: /opt/nikos/bin/nikos

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nikos-archive
          path: /opt/nikos
          retention-days: 1

  verify-glibc:
    name: Check GLIBC references
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download the nikos artifact
        uses: actions/download-artifact@v3
        with:
          name: nikos-archive
          path: /opt/nikos

      - name: Fail if there are references to GLIBC >= 2.18
        run: objdump -p /opt/nikos/bin/nikos | egrep -zqv 'GLIBC_2\.(1[8-9]|[2-9][0-9])'

  tests-v2:
    name: Tests V2
    needs: build
    runs-on: macos-12
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: .ci_build/requirements.txt

      - name: Install pip dependencies
        run: pip install -r .ci_build/requirements.txt

      - name: Download the nikos artifact
        uses: actions/download-artifact@v3
        with:
          name: nikos-archive
          path: .ci_build/nikos-archive

      - name: Set nikos binary executable
        run: |
          chmod +x .ci_build/nikos-archive/bin/nikos

      - name: Setup VM
        working-directory: .ci_build
        run: |
          vagrant up
          vagrant ssh -c /vagrant/setup.sh
