---
name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build nikos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - name: Build nikos
        run: bash .ci_build/build_install_nikos.sh .

      - name: Verify build
        run: /opt/nikos/bin/nikos

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nikos-binary
          path: /opt/nikos/bin/nikos
          retention-days: 1

  verify-glibc:
    name: Check GLIBC references
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download the nikos artifact
        uses: actions/download-artifact@v3
        with:
          name: nikos-binary
          path: /opt/nikos/bin

      - name: Fail if there are references to GLIBC >= 2.18
        run: objdump -p /opt/nikos/bin/nikos | egrep -zqv 'GLIBC_2\.(1[8-9]|[2-9][0-9])'

  test-fixture-rhel:
    name: Fixture test RHEL
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Download the nikos artifact
        uses: actions/download-artifact@v3
        with:
          name: nikos-binary
          path: /opt/nikos/bin

      - name: Fix permission
        run: |
          sudo chmod +x /opt/nikos/bin/nikos

      - name: Test RHEL CI
        continue-on-error: true
        run: |
          make -f fixtures/Makefile test.rhel.ci
