---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build nikos
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.25"

      - name: Cache Go modules
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build nikos
        run: bash .ci_build/build_install_nikos.sh .

      - name: Verify build
        run: /opt/nikos/bin/nikos

      - name: Upload artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: nikos-archive
          path: /opt/nikos
          retention-days: 1

  molecule-tests:
    name: Molecule tests
    needs: build
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            "fedora",
            "centos",
            "opensuse",
            "debian",
            "ubuntu",
            "oracle",
            "amazon-linux",
          ]
        test_type: ["host", "container"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"
          cache-dependency-path: .ci_build/requirements.txt

      - name: Install pip dependencies
        run: |
          pip install -r .ci_build/requirements.txt

      - name: Install virtualbox and vagrant
        run: |
          sudo lsmod | grep kvm_amd | sudo xargs rmmod
          sudo lsmod | grep kvm | sudo xargs rmmod
          
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes -o /usr/share/keyrings/oracle-virtualbox-2016.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] https://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list

          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

          sudo apt-get update && sudo apt-get install gcc-12 virtualbox-7.2 vagrant

      - name: Download the nikos artifact
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: nikos-archive
          path: tests/molecule/resources/playbooks/nikos-archive

      - name: Set nikos binary executable
        run: |
          chmod +x tests/molecule/resources/playbooks/nikos-archive/bin/nikos

      - name: Run molecule test
        working-directory: tests
        # Fix breakage caused by https://github.com/ansible/molecule/pull/4380
        # See https://github.com/ansible-community/molecule-plugins/issues/301
        run: |
          export PYTHON_LIB_PATH="$(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')"
          export ANSIBLE_LIBRARY="${PYTHON_LIB_PATH}/molecule/provisioner/ansible/plugins/modules:${PYTHON_LIB_PATH}/molecule_plugins/vagrant/modules:${HOME}/.ansible/plugins/modules:/usr/share/ansible/plugins/modules"
          export ANSIBLE_FILTER_PLUGINS="${PYTHON_LIB_PATH}/molecule/provisioner/ansible/plugins/filter:${HOME}/.ansible/plugins/filter:/usr/share/ansible/plugins/filter"
          molecule test -s ${{ matrix.platform }}-${{ matrix.test_type }}
