---
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    name: Build nikos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build nikos
        run: bash .ci_build/build_install_nikos.sh .

      - name: Verify build
        run: /opt/nikos/bin/nikos

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nikos-archive
          path: /opt/nikos
          retention-days: 1

  verify-glibc:
    name: Check GLIBC references
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download the nikos artifact
        uses: actions/download-artifact@v4
        with:
          name: nikos-archive
          path: /opt/nikos

      - name: Fail if there are references to GLIBC >= 2.18
        run: objdump -p /opt/nikos/bin/nikos | egrep -zqv 'GLIBC_2\.(1[8-9]|[2-9][0-9])'

  molecule-tests:
    name: Molecule tests
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            "fedora",
            "centos",
            "opensuse",
            "debian",
            "ubuntu",
            "oracle",
            "amazon-linux",
          ]
        test_type: ["host", "container"]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache-dependency-path: .ci_build/requirements.txt

      - name: Install pip dependencies
        run: |
          pip install -r .ci_build/requirements.txt

      - name: Install virtualbox and vagrant
        run: |
          wget -O- https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor --yes -o /usr/share/keyrings/oracle-virtualbox-2016.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/oracle-virtualbox-2016.gpg] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list

          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

          sudo apt-get update && sudo apt-get install gcc-12 virtualbox-7.0 vagrant

      - name: Download the nikos artifact
        uses: actions/download-artifact@v4
        with:
          name: nikos-archive
          path: tests/molecule/resources/playbooks/nikos-archive

      - name: Set nikos binary executable
        run: |
          chmod +x tests/molecule/resources/playbooks/nikos-archive/bin/nikos

      - name: Run molecule test
        working-directory: tests
        run: molecule test -s ${{ matrix.platform }}-${{ matrix.test_type }}
